#pragma once
#include "nlohmann/json.hpp"
#include "SaveData.h"

enum Bunyip : int {
    SHADOW = 0,
    EXTREME = 1
};

enum Mission : int {
	SAVE_THE_DREAMING = 1,
	RESCUE_THE_GENERAL = 2,
	BROWN_KIWI_DOWN = 3,
	THE_BIG_RACE = 5,
	RESCUE_JULIUS = 10,
    HEINOUS_HEXAQUIN = 12,
    MEET_SHAZZA = 13,
    SEA_CHANGE = 14,
    BATTLE_ARENA_GAMMA = 19,
    THE_SEARCH_FOR_STEVE = 23,
    FIND_THE_SHADOWRING = 24,
    BATTLE_ARENA_ZETA = 26,
    GO_FIND_BOSS_CASS = 70,
    EXPERI_MENTAL_CART = 6,
    DEMOLITION_DERBY = 16,
    DENNIS_DILEMMA = 15,
    RESPECT_EFFECT = 27,
    REDBACK_STASH = 28,
    QUINKAN_ARMADA = 7,
    EGG_HUNT = 8,
    POWER_STRUGGLE = 17,
    MELTDOWN = 18,
    RANGER_ENDANGER = 29,
    REDBACK_RUNDOWN = 30,
    ALL_YOUR_BASE = 11,
    AERO_COAST_GUARD = 21,
    WRATH_OF_THE_DRAGONQUIN = 22,
    FOREST_FIREPOWER = 31,
    QUINKING = 34,
    QUINKING_PRE = 33,
    KARLOS_MISSION = 84,
    CRAB_MISSION = 83,
    SLY_MISSION = 82,
    DUKE_MISSION = 81,
    SWAMP_MISSION = 80,
    CRAB_INTRO = 99,
};

NLOHMANN_JSON_SERIALIZE_ENUM(Mission, {
    {Mission::QUINKAN_ARMADA, "QUINKAN_ARMADA"},
    {Mission::EGG_HUNT, "EGG_HUNT"},
    {Mission::POWER_STRUGGLE, "POWER_STRUGGLE"},
    {Mission::MELTDOWN, "MELTDOWN"},
    {Mission::RANGER_ENDANGER, "RANGER_ENDANGER"},
    {Mission::REDBACK_RUNDOWN, "REDBACK_RUNDOWN"},
});

NLOHMANN_JSON_SERIALIZE_ENUM(MissionState, {
    {MissionState::UNAVAILABLE, "UNAVAILABLE"},
    {MissionState::AVAILABLE, "AVAILABLE"},
	{MissionState::ACTIVE, "ACTIVE"},
	{MissionState::REPLAYABLE, "REPLAYABLE"},
    {MissionState::COMPLETE, "COMPLETED"},
});