#pragma once
#include "apclient.hpp"
#include <map>
#include <iostream>
#include <filesystem>
#include <vector>
#include <string>
#include <array>
#include "imgui.h"
#include <cstdint>
#include "imgui_impl_opengl3.h"
#include "imgui_internal.h"
#include "imgui_stdlib.h"
#include "imgui_impl_win32.h"
#include "../TygerMemory3/Core.h"
#include "../TygerMemory3/Logging.h"
#include <../TygerMemory3/MKObject.h>
#include <../TygerMemory3/Missions.h>
#include <../TygerMemory3/SaveData.h>
#include <../TygerMemory3/MKUI.h>
#include "../TygerFramework/TygerFrameworkAPI.h"
#include "../TygerFramework/TygerFrameworkAPI.hpp"