#pragma once
#include "apclient.hpp"
#include <map>
#include <iostream>
#include <filesystem>
#include <vector>
#include <string>
#include <array>
#include "imgui.h"
#include <cstdint>
#include "imgui_impl_opengl3.h"
#include "imgui_internal.h"
#include "imgui_stdlib.h"
#include "imgui_impl_win32.h"
#include "../TygerMemory2/Core.h"
#include "../TygerMemory2/Logging.h"
#include <../TygerMemory2/MKObject.h>
#include <../TygerMemory2/Missions.h>
#include <../TygerMemory2/SaveData.h>
#include <../TygerMemory2/MKUI.h>
#include <../TygerMemory2/MemoryLinkedList.h>
#include "../TygerFramework/TygerFrameworkAPI.h"
#include "../TygerFramework/TygerFrameworkAPI.hpp"